name: Changelog on Release

on:
  release:
    types: [published, edited]
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (optional for manual run)"
        required: false

# Один ран на тег/ручной запуск
concurrency:
  group: changelog-${{ github.ref || inputs.tag || 'manual' }}
  cancel-in-progress: false

# Права для создания PR и коммитов
permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false   # не протекаем GITHUB_TOKEN

      - name: Setup git author (cosmetic)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Resolve tag
        id: tag
        shell: bash
        run: |
          TAG="${{ github.event.release.tag_name || inputs.tag }}"
          if [[ -z "$TAG" ]]; then
            echo "No tag provided; skipping."
            echo "skip=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          if ! git rev-parse -q --verify "refs/tags/$TAG" >/dev/null; then
            echo "Tag '$TAG' not found; skipping."
            echo "skip=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Compute range
        if: steps.tag.outputs.skip != 'true'
        id: range
        shell: bash
        run: |
          TAG="${{ steps.tag.outputs.tag }}"
          # Берём предыдущий тег по дате создания (исключая текущий)
          PREV="$(git tag --sort=-creatordate | grep -v -e "^${TAG}$" | head -n1 || true)"
          echo "prev=$PREV" >> "$GITHUB_OUTPUT"

      - name: Generate CHANGELOG.md
        if: steps.tag.outputs.skip != 'true'
        shell: bash
        run: |
          set -euo pipefail
          TAG="${{ steps.tag.outputs.tag }}"
          PREV="${{ steps.range.outputs.prev }}"
          {
            echo "# Changelog"
            echo
            echo "## $TAG"
            echo
            if [[ -n "$PREV" ]]; then
              # с предыдущего тега до этого тега
              git log --no-merges --pretty="* %s (%h) by %an" "$PREV..$TAG"
            else
              # если предыдущего тега нет — только текущий диапазон
              git log --no-merges --pretty="* %s (%h) by %an" "$TAG"
            fi
          } > CHANGELOG.md

      - name: Create Pull Request
        if: steps.tag.outputs.skip != 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          # Используем личный PAT, сохранённый как репо-секрет ACTIONS_WRITER_PAT
          token: ${{ secrets.ACTIONS_WRITER_PAT }}
          branch: docs/changelog/${{ steps.tag.outputs.tag }}
          base: master
          title: "docs(changelog): ${{ steps.tag.outputs.tag }}"
          commit-message: "docs(changelog): add CHANGELOG for ${{ steps.tag.outputs.tag }}"
          body: |
            Changelog for **${{ steps.tag.outputs.tag }}**.
            Auto-generated by workflow.
          add-paths: |
            CHANGELOG.md
          # чтобы повторный ран обновлял существующий PR
          delete-branch: false
          draft: false
