name: Changelog on Release

on:
  release:
    types: [published, edited]
  workflow_dispatch:            # ручной запуск из Actions
    inputs:
      tag:
        description: "Tag name to (re)build notes for. Leave empty to use latest release"
        required: false

permissions:
  contents: write               # нужно для обновления release notes
  pull-requests: read
  issues: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history for tags/PRs)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Resolve tag
        id: meta
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [ -n "${{ github.event.release.tag_name }}" ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          elif [ -n "${{ inputs.tag }}" ]; then
            echo "tag=${{ inputs.tag }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=$(gh release view --json tagName -q .tagName)" >> "$GITHUB_OUTPUT"
          fi
          echo "Using tag: $(cat $GITHUB_OUTPUT)"

      - name: Build changelog from PRs
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: .github/changelog-config.json
          toTag: ${{ steps.meta.outputs.tag }}
          ignorePreReleases: true
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Update release notes
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          body: ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
