name: Changelog on Release

on:
  release:
    types: [published, edited]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (optional for manual run)'
        required: false

concurrency:
  group: changelog-${{ github.ref || inputs.tag || 'manual' }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:           # ровно то, что нужно для PR
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false  # <-- важное требование semgrep

      - name: Setup git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Resolve tag
        id: tag
        run: |
          TAG="${{ github.event.release.tag_name || inputs.tag }}"
          if [ -z "$TAG" ]; then
            echo "No tag provided; skipping."
            echo "skip=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          if ! git rev-parse -q --verify "refs/tags/$TAG" >/dev/null; then
            echo "Tag '$TAG' not found; skipping."
            echo "skip=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Compute range
        if: steps.tag.outputs.skip != 'true'
        id: range
        run: |
          TAG="${{ steps.tag.outputs.tag }}"
          PREV=$(git tag --sort=-creatordate | grep -v "^$TAG$" | head -n1 || true)
          echo "prev=$PREV" >> $GITHUB_OUTPUT

      - name: Generate CHANGELOG.md
        if: steps.tag.outputs.skip != 'true'
        run: |
          TAG="${{ steps.tag.outputs.tag }}"
          PREV="${{ steps.range.outputs.prev }}"
          {
            echo "# Changelog"
            echo
            echo "## $TAG"
            echo
            if [ -n "$PREV" ]; then
              git log --pretty="* %s (%h) by %an" "$PREV..$TAG"
            else
              git log --pretty="* %s (%h) by %an" "$TAG"
            fi
          } > CHANGELOG.md

      - name: Create Pull Request
        if: steps.tag.outputs.skip != 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: docs/changelog/${{ steps.tag.outputs.tag }}
          commit-message: "docs(changelog): add CHANGELOG for ${{ steps.tag.outputs.tag }}"
          title: "docs(changelog): ${{ steps.tag.outputs.tag }}"
          body: |
            Changelog for **${{ steps.tag.outputs.tag }}**
            Auto-generated by workflow.
          base: master
          add-paths: |
            CHANGELOG.md
