name: Changelog on Release

on:
  release:
    types: [published, edited]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build CHANGELOG.md
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          # при желании можно указать конфиг:
          # configuration: .github/changelog-config.json
          toTag: ${{ github.event.release.tag_name || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update file & create working branch
        id: update
        shell: bash
        run: |
          echo "${{ steps.changelog.outputs.changelog }}" > CHANGELOG.md
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # уникальная ветка, НИКОГДА не совпадёт с base
          TAG="${{ github.event.release.tag_name || github.ref_name }}"
          BR="docs/changelog-${TAG}-${{ github.run_number }}"
          git checkout -B "$BR"

          git add CHANGELOG.md
          if git diff --cached --quiet; then
            echo "no_changes=true"  >> $GITHUB_OUTPUT
          else
            git commit -m "docs(changelog): update for ${TAG}"
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi
          echo "branch=$BR" >> $GITHUB_OUTPUT
          echo "tag=$TAG"   >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.update.outputs.no_changes == 'false'
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          # ЯВНО указываем base вашей репы
          base: master
          branch: ${{ steps.update.outputs.branch }}
          title: "docs(changelog): ${{ steps.update.outputs.tag }}"
          body: "Auto-generated changelog for ${{ steps.update.outputs.tag }}"
          labels: changelog, automated
          delete-branch: true

      - name: Job summary (PR link)
        run: |
          if [ -n "${{ steps.cpr.outputs.pull-request-url }}" ]; then
            echo "PR **#${{ steps.cpr.outputs.pull-request-number }}** → ${{ steps.cpr.outputs.pull-request-url }}" >> $GITHUB_STEP_SUMMARY
          else
            echo "No changes to commit — PR not created." >> $GITHUB_STEP_SUMMARY
          fi
