name: Release Drafter

on:
  push:
    branches: [ master ]
  pull_request_target:
    types: [opened, reopened, synchronize, edited]
    paths:
      - '.github/**'          # реагируем только на изменения в .github
  workflow_dispatch: {}

concurrency:
  group: release-drafter-${{ github.ref }}
  cancel-in-progress: false

jobs:
  update_release_draft:
    # Не запускать «повышенный» pull_request_target для форков
    if: ${{ github.event_name != 'pull_request_target' || github.event.pull_request.head.repo.fork == false }}
    runs-on: ubuntu-latest
    permissions:           # least-privilege на уровне job
      contents: write
      pull-requests: read
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
