name: Release Drafter

on:
  push:
    branches: [ master ]                       # твоя default-ветка
  pull_request_target:
    types: [opened, reopened, synchronize, edited, labeled, unlabeled, closed]
  workflow_dispatch: {}                         # ручной запуск из Actions

permissions:
  contents: write                               # нужно, чтобы писать/обновлять draft release
  pull-requests: read

concurrency:
  group: release-drafter-${{ github.ref }}
  cancel-in-progress: false

jobs:
  update_release_draft:
    name: update_release_draft
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          # конфиг Release Drafter (лежит в .github/release-drafter.yml)
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}