name: Release Drafter

on:
  push:
    branches:
      - master        # твой default branch
  pull_request_target:
    types: [opened, reopened, synchronize, edited]
  workflow_dispatch: {}      # <- кнопка "Run workflow"

permissions:
  contents: write            # нужно для записи драфта релиза
  pull-requests: read

concurrency:
  group: release-drafter-${{ github.ref }}
  cancel-in-progress: false

jobs:
  update_release_draft:
    name: update_release_draft
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          # путь к конфигу Release Drafter (по умолчанию .github/release-drafter.yml)
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
